package dev.iancdev.hudglasses

import android.media.MediaRecorder

data class RadarDot(
    val trackId: Int = 0,
    val freqHz: Float,
    val radarX: Float,
    val radarY: Float,
    val intensity: Float,
)

data class HudState(
    val serverUrl: String = "ws://10.19.130.231:8765",
    val eventsConnected: Boolean = false,
    val sttConnected: Boolean = false,
    val phoneAudioFallbackEnabled: Boolean = false,
    val phoneHapticsEnabled: Boolean = true,
    val phoneDirectionHapticsEnabled: Boolean = false,
    val phoneMicSource: Int = MediaRecorder.AudioSource.MIC, // -1 = auto
    val phoneMicActiveSource: Int? = null,
    val phoneMicChannels: Int = 0,
    val phoneMicRmsLeft: Float = 0f,
    val phoneMicRmsRight: Float = 0f,
    val phoneMicStereoDiffRatio: Float = 0f,
    val phoneMicCorrelation: Float = 0f,
    val glassesConnected: Boolean = false,
    val serverStatus: String = "",
    val sttStatus: String = "",
    val sttError: String = "",
    val esp32ConnectedLeft: Boolean = false,
    val esp32ConnectedRight: Boolean = false,
    val wristbandConnected: Boolean = false,
    val externalHapticsEnabled: Boolean = false,
    val externalHapticsLeftConnected: Boolean = false,
    val externalHapticsRightConnected: Boolean = false,
    val vitureInitResult: Int? = null,
    val vitureImuState: Int? = null,
    val viture3dState: Int? = null,
    val vitureImuFrequency: Int? = null,
    val alarmRmsThreshold: Float = 0.02f,
    val fireRatioThreshold: Float = 0.18f,
    val hornRatioThreshold: Float = 0.20f,
    val keywordsCsv: String = "look out",
    val keywordCooldownS: Float = 5f,
    val keywordAlert: String = "",
    val directionDeg: Float = 0f,
    val intensity: Float = 0f,
    val radarX: Float = 0f,
    val radarY: Float = 0f,
    val radarDots: List<RadarDot> = emptyList(),
    val glowEdge: String = "top",
    val glowStrength: Float = 0f,
    val fireAlarm: String = "idle",
    val carHorn: String = "idle",
    val siren: String = "idle",
    val subtitlePartial: String = "",
    val subtitleLines: List<String> = emptyList(),
    val hudWidthPx: Int? = null,
    val hudHeightPx: Int? = null,
    val hudDensityDpi: Int? = null,
)
