package dev.iancdev.hudglasses

data class HudState(
    val serverUrl: String = "ws://192.168.1.2:8765",
    val eventsConnected: Boolean = false,
    val sttConnected: Boolean = false,
    val phoneAudioFallbackEnabled: Boolean = false,
    val glassesConnected: Boolean = false,
    val serverStatus: String = "",
    val sttStatus: String = "",
    val sttError: String = "",
    val esp32ConnectedLeft: Boolean = false,
    val esp32ConnectedRight: Boolean = false,
    val wristbandConnected: Boolean = false,
    val vitureInitResult: Int? = null,
    val vitureImuState: Int? = null,
    val viture3dState: Int? = null,
    val vitureImuFrequency: Int? = null,
    val alarmRmsThreshold: Float = 0.02f,
    val fireRatioThreshold: Float = 0.18f,
    val hornRatioThreshold: Float = 0.20f,
    val keywordsCsv: String = "look out",
    val keywordCooldownS: Float = 5f,
    val keywordAlert: String = "",
    val directionDeg: Float = 0f,
    val intensity: Float = 0f,
    val radarX: Float = 0f,
    val radarY: Float = 0f,
    val glowEdge: String = "top",
    val glowStrength: Float = 0f,
    val fireAlarm: String = "idle",
    val carHorn: String = "idle",
    val subtitlePartial: String = "",
    val subtitleLines: List<String> = emptyList(),
)
